sambastudio:
  snapi_path: ""
  rdu_arch: "sn40"

dataset:
  dataset_name: "MITRE dataset - Snsdk wrapper"
  dataset_description: "mitre dataset test"
  dataset_path: /Users/rodrigom/Desktop/aisk/finetuning/mitre
  dataset_apps_availability: 
  - "E5 Mistral Embedding"
  - "Text Embedding" 
  dataset_job_types:
    - "train"
  dataset_source_type: "localMachine"
  dataset_filetype: "hdf5"
  dataset_url: ""
  dataset_language: "english"
  dataset_metadata:
    labels_file: ""
    train_filepath: ""
    validation_filepath: ""
    test_filepath: ""
  
project: 
  project_name: "Project - Snsdk wrapper test"
  project_description: "this project will be used to test e2e fine-tuning pipeline implementation"

job:
  job_name: "snsdk_wrapper_test_job"
  job_description: "snsdk wrapper test training project"
  job_type: "train"
  model: "E5 Large V2"
  model_version: 1
  parallel_instances: 1
  load_state: false
  sub_path: ""
  hyperparams:
      batch_size: 256
      learning_rate: 0.00001
      logging_steps: 1
      max_epochs: 1
      num_iterations: 5
      save_epoch: 1
      save_steps: 3
      seed: 123
      train_n_passages: 8
      warmup_steps: 0
      weight_decay: 0.1

model_checkpoint:
  model_checkpoint_id: "f0801cd8-b47d-40bd-ab22-c469cde42607-3" #set after listing the generated checkpoints after training 
  model_name: "snsdk_wrapper_test_e5_large_v2_finetuned_mitre"
  model_description: "wrapper test for e5 finetuned on mitre"
  model_version: 1
  model_type: "finetuned"

endpoint:
  endpoint_name: "wrapper-test-e5-finetuned-on-mitre"
  endpoint_description: "wrapper test e5 finetuned on mitre"
  endpoint_instances: 1
  hyperparams: null